---
author:
  - 'Sholto Maud <sholto.maud@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: chr
no_index:
  directory:
    - inc
requires:
  Cwd: 0.01
  Env: 0.01
  FindBin: 0.01
  Git::Wrapper: 0.01
  Pod::Select: 0.01
  Time::Local: 0.01
  local::lib: 0.01
  perl: 5.6.0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/shotlom/chr.git
version: 0.01
